export {default as create}      from "api-common/api/organization/fixed_phrase/create"
export {default as delete}      from "api-common/api/organization/fixed_phrase/delete"
export {default as read}        from "api-common/api/organization/fixed_phrase/read"
export {default as subscribe}   from "api-common/api/organization/fixed_phrase/subscribe"
export {default as unsubscribe} from "api-common/api/organization/fixed_phrase/unsubscribe"
export {default as update}      from "api-common/api/organization/fixed_phrase/update"
